export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';


export const GET_POST = 'GET_POST';
export const GET_POST_CATEGORIES = 'GET_POST_CATEGORIES';
export const GET_POST_CATEGORY = 'GET_POST_CATEGORY';
export const GET_2_POSTS = 'GET_2_POST';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const POST_LOADING = 'POST_LOADING';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_PAGES = 'GET_POSTS_PAGES';
export const GET_POST_COMMENTS_PAGES = 'GET_POST_COMMENTS_PAGES';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const PLAYER_LOADING = 'PLAYER_LOADING';
export const GET_PLAYER = 'GET_PLAYER';
export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_PLAYERS_PAGES = 'GET_PLAYERS_PAGES';
export const GET_PLAYERS_POSITIONS = 'GET_PLAYERS_POSITIONS';

export const MATCH_LOADING = 'MATCH_LOADING';
export const GET_MATCH = 'GET_MATCH';
export const GET_MATCHES = 'GET_MATCHES';
